services:
  - type: web
    name: eon-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: your-jwt-secret-key
      - key: DATABASE_URL
        value: your-database-url